### ISSUE TITLE
Wrong document for locale

### ISSUE THREAD

**Issue by wachterjohannes** [sulu-io/sulu-document-manager#41]
if you load a document with any locale this document will be stored in the `DocumentRegistry` with this locale.
If you load in the same request the same uuid as document with a different locale you get a document with the first locale. this seems to be a bug in the `DocumentRegistry`.

Because the `RegistratorSubscriber` ignores the given locale and loads any document out of the registry.

My Suggestion would be to change this behavior to this: https://github.com/sulu-io/sulu-document-manager/pull/42

**Comment by wachterjohannes** [comment]
@dantleech what do you think? /cc @danrot

**Comment by dantleech** [comment]
I don't think this is a bug with the DocumentRegistry.

The Document is the object. The essential role of the document registry is to return the object. If an object is loaded in a different locale, it is stil the same object. The DocumentRegistry doesn't actually care what is _in_ the object.

The `DocumentManager` does, perhaps confusingly, also track the current locale of the object. But this is a separate responsibility.

What you describe should not happen because the locale should be updated (and the document _rehydrated_) if the locale is [different from the currently registered locale for the document](https://github.com/sulu-io/sulu-document-manager/blob/query_builder_final/lib/Subscriber/Core/RegistratorSubscriber.php#L109).

If you could add a failing test I could perhaps look at this if you cannot find it.

**Comment by wachterjohannes** [comment]
i will take a look today ... but for me its not the same document because the locale is a big part of it and should also be tracked in the registry! but i will take a look at a testcase today!

**Comment by wachterjohannes** [comment]
hmm it is not a simple `DocumentManager` problem. because it seams to be a problem in combination with sulu´s `StructureSubscriber`.

But for me it should be a different Object for "en" or "de". Because if a bigger routine get a document for "en" and a sub-routing uses the same uuid to get the document in "de" the bigger routine did not recognize that his document has changed and the locale of it is different. so i think the locale should also be used to determine the document in the Registry. what do you think @dantleech @danrot ? i have created a failing testcase in PR #44

**Comment by dantleech** [comment]
The document and the object are the same thing. You can look at the object in different ways (e.g. with differnet locales) but essentially it is the same object representing the same subject. The object ID maps directly to the node UUID. If you had lots of different representations of the document floating about it would become difficult to manage.

One thing that springs to mind is that if you have 10 objects representing one document (i.e. 10 locales), each one had 3 translated fields and 3 non-translated fields, how should conflicts be resolved if one of them changes a non-translated field?

The PHPCR-ODM, Doctrine ORM (with the Gedmo extensions), and does Propel ORM all operate with this identity model.

The issue you mention is indeed a small issue (but one shared with all other PHP ORMs that I am aware of), but as long as an object has both "translated" and non-translated properties, conflcit- at least - is going to be an issue. I am not sure how many other problems would be caused by changing the basic design of the document registry.

**Comment by wachterjohannes** [comment]
ok i will try to implement a testcase in sulu! maybe you have time to take a look at this (:

**Comment by dantleech** [comment]
ok, found what _causes_ and reveals this issue. The `PhpcrAccessControlProvider` resets the "original locale" to `null` by calling `find($path)` (i.e. without a locale). Removing this check restores the "correct" behavior.

Looking at a fix.

**Comment by dantleech** [comment]
I have created a PR on the document manager: https://github.com/sulu-io/sulu-document-manager/pull/46

This allows find to be called with a `redryhate` option set fo `false`. This prevents the object being rehydrated, so the option just had to be added to call from `PhpcrAccessControlProvider`.

I also created [this issue](https://github.com/sulu-io/sulu-document-manager/issues/45) about global state and options for discussion - we certainly need to improve the current way options are handled regarding state - there are certainly bugs waiting to be discovered currently.

I think that, within the scope of the current document mangager, the `rehydrate` option makes sense. Let's discuss in the DM PR.
